### ISSUE TITLE
I think its good to be true then I found out there a flaw on this.

### ISSUE THREAD

**Issue by Succubussix** [Darkratos/Spoofed-Call#1]
```
int __cdecl main(int argc, const char **argv, const char **envp)
{
  _DWORD *v4; // [esp+0h] [ebp-4h]

  v4 = operator new(4u);
  *v4 = sub_401000;
  sub_401060(v4, sub_401010, 1, 1, 1, 3);
  system("pause");
  return 0;
}
```
```
	spoofed_call* sc = new spoofed_call(spoof_method::existing, (uintptr_t)call_esi);
	sc->stdcall_fn((uintptr_t)hideme, 1, 1, 1, 3);
```
the param hideme became like that because you pass it as a parameter also. you hide the call but u dint hide the param.

hideme = 0x401010
stdcall_fn = 0x401060

**Comment by Darkratos** [comment]
Yes, but that's intended. The user is supposed to hide/obfuscate their binaries with their own protections or 3rd parties'.
The intent of my code is to hide the return from the stack, which you can debug and check out for yourself.
As for the protection, maybe consider virtualizing the code. That should keep most people out of it.
Hope this clears it.
